### ISSUE TITLE
Problem with "seg"

### ISSUE THREAD

**Issue by monosakkarid** [cookfish/segvoice#3]
I am still a bit confused on your code. 

You first start with:
"python main.py train /path/to/wav"   , where "path/to/wav" is one or more wave files which are converted into a mdl fil after running the command. 

In the next segment you write:
"python main.py seg /generated/model/file/path /path/to/wav"
Is "/generated/model/file/path"  the mdl file I have trained, and "/path/to/wav" the new wave file I wish to test the data on? I have some problems running this part of the code. I tried code:

python main.py train A.wav
python main.py seg A.mdl  B.wav

I get error "TypeError: slice indices must be integers or None or have an __index__ method"

Thanks for any response!

**Comment by cookfish** [comment]
ok, you should choose train_A.wav as trainning data because it's much longer. And choosing mix.wav as seg data beacause it's mixture of A and B. The reason of that error you got is B.wav not convering A's voice.
